title: "Marshallia"
description: "PhD Student in Machine Learning | Computer Vision & Generative AI"
markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
github: marshallia
linkedin: maysa-marshallia
email: marshallia@g.ncu.edu.tw
author:
  name: "Maysa Marshallia"
  email: "marshallia@g.ncu.edu.tw"
  
# Navigation links
header_pages:
  - index.md
  - projects.md
  - publications.md

